### ISSUE TITLE
What do you think to display together mix typesafe and typeunsafe?

### ISSUE THREAD

**Issue by satoren** [satoren/lua_binding_benchmark#11]
I think that should be displayed separately.
When in typeunsafe library mistake of argument it occurs becomes undefined behavior rather than an error.

**Comment by vapourismo** [comment]
There are edge cases where type-checking is not required, so it might be useful.

Though in general, it is not a good idea to skip type-checking when interacting with a dynamically-typed language.

**Comment by satoren** [comment]
I think so too.

**Comment by satoren** [comment]
So I think that it is wrong to compare on an equal footing.

**Comment by ThePhD** [comment]
I think it depends. For constant development, you want the safeties on (perhaps by default during debug builds). But, for release code, you generally want to take all of the safeties off once you've thoroughly used / tested the code, even for a dynamic language.

**Comment by vapourismo** [comment]
If you can turn off type-safety in production, you shouldn't have used a dynamically-typed language in the first place.
