### ISSUE TITLE
How do I properly update the webpage?

### ISSUE THREAD

**Issue by ThePhD** [satoren/lua_binding_benchmark#3]
Quick question:

When I generate the benchmark data, do I pull the results files from a continous integration build like travis-ci, commit the result_system_info.txt and results.csv back into the repo, and then the webpages automatically adjust / update to that? Or, do I need to modify the ghpages directly?

**Comment by satoren** [comment]
is not automatically.

Since the well build time has been variability by the load of travis-ci. I don't know whether it results can be trusted.

**Comment by satoren** [comment]
I tried to put the experimental automatic update

**Comment by ThePhD** [comment]
Neat! The numbers do seem a tad bit strange and a little too... rounded, to be frank. Everything is a multiple of 10.

**Comment by satoren** [comment]
Yes... maybe AWS does not support high resolution timer and tick is 10ms  (CONFIG_HZ=100)
