### ISSUE TITLE
Chart suggestion

### ISSUE THREAD

**Issue by r-lyeh-archived** [satoren/lua_binding_benchmark#8]
It is hard to interpret the results between kaguya, sol2, luwra and a few others (the bars look similar because the numbers are quite close).

I think it would be better either to 
a) change the bar scale to something bigger, 
or
b) subtract plain Lua results from every wrapper result (so the overhead gets displayed instead).

**Comment by vapourismo** [comment]
The bars are close in length, because the timings are very close. There is a table below the chart that displays all the timings. It is also sortable.

**Comment by satoren** [comment]
![sepgraph](https://cloud.githubusercontent.com/assets/11295976/15713473/8b3a8d32-2851-11e6-90db-12bb24e02460.png)

Split by type. How about this?

**Comment by ThePhD** [comment]
That looks amazingly good actually!

**Comment by vapourismo** [comment]
I am inclined to agree.

**Comment by r-lyeh-archived** [comment]
:+1:
