### ISSUE TITLE
Error is large when running on travis-ci

### ISSUE THREAD

**Issue by satoren** [satoren/lua_binding_benchmark#9]
| Library | global table | table chain | c function call | lua function call | C++ object member call | Returning a class object |
| --- | --- | --- | --- | --- | --- | --- |
| plain api(build #112) | 370 | 870 | 270 | 710 | 1530 | **290** |
| plain apii(build #113) | 370 | 780 | 280 | 710 | 1450 | **510** |

code is not changed, but time different is large.:cold_sweat:

**Comment by ThePhD** [comment]
I wonder if I can get a dedicated VM to perform the measurements on a much more isolated environment? I have a DigitalOcean instance lying around doing not-much-of-anything-important.

**Comment by ThePhD** [comment]
https://developer.github.com/v3/activity/events/types/#pushevent Looks like if I make a quick python thing to set up a receiving server and grab data, I can run the benchmarks and then push it to the gh-pages directory. Does that sound fair?

**Comment by vapourismo** [comment]
Before you switch, I urge you to test it manually. DigitalOcean droplets and Travis' build instances aren't so different. They are either KVM-enabled QEMU machines or Docker containers. The droplets _might_ have a dedicated CPU. Nevertheless they both run on shared hardware.

**Comment by satoren** [comment]
Good point. I can create private server for solve that problem. Because this machine is not often used.
But that can not see benchmark process except me. I think it is not fair.

**Comment by satoren** [comment]
Feeling stable since add sleep before benchmarks.

**Comment by vapourismo** [comment]
I can't reproduce these benchmarks. I am aware that this seems absolutely biased, but Luwra is the fastest in every category, except in the two table categories, on every machine I own. Its mosly a 2-10% gap. Even if we assume the gap is -10% to 10%, the error on the automated build instances is still far too big and doesn't match that.

I suggest that one person performs the benchmark once a week (always with most up to date libraries) and publishes that.

**Comment by satoren** [comment]
I understand. Quite different by enviroment, e.g. lua version.

**Comment by satoren** [comment]
How about executing benchmark on client side web browser by emscripten?

**Comment by ThePhD** [comment]
I'm not sure how viable that is, and if it wouldn't have the same problems with automatic benchmarks in a droplet or travis-ci...!

**Comment by satoren** [comment]
http://satoren.github.io/lua_binding_benchmark/em_test/
Wrote test page.
